drop database college_info;
#drop is for deleting table;
CREATE DATABASE COLLEGE_INFO;
-- alwaus select then run--
USE COLLEGE_INFO;
#USE MEANS FROM NOW ON EVERYTHING WILL BE IN THIS DATABASE
CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT NOT NULL
);
#COLN NAME DATATYPE CONSTRAINTS
INSERT INTO STUDENT values(2,"HELLO",56);
#INSERT USED TO INSERT DATA INTO TABLE
INSERT INTO STUDENT values(3,"HELLO",56);
INSERT INTO STUDENT values(4,"HELLO",56);
INSERT INTO STUDENT values(1,"HELLO",56);
SELECT * FROM STUDENT;
#SELECT * SELECT ENTIRE TABLE STUDENT
#VARCHAR ONLY TAKES PLACE OF WHAT OF THEIR CHARACTER LENGTH BUT CHAR TAKES WHOLE LENGTH
#UNSIGNED 0 TO 255
#SIGNED -128 TO -127
#TINYINT UNSIGNED
cREATE DATABASE IF NOT EXISTS COLLEGE_INFO;  
#ALWYS USE IF NOT EXIST TO PREVENT FROM ERROR
#DROP DATABASE IF NOT EXISTS;
SHOW databases; 
#USED TO SHOW ALL DATABASES INSIDE SQL;
SHOW TABLES;
#USED TO SHOW ALL  TABLES INSIDE DATABASES
#SCHEMA=>DESING=>COLUMN
#PK: NOT NULL UNIQUE

#CAN INSERT INTO SELECTED COLUMN USING INSERT
INSERT INTO STUDENT(ID,AGE)
 VALUES(12,56),(15,98);
 

